### ISSUE TITLE
FileNotFoundError: [WinError 2] with guild_run

### ISSUE THREAD

**Issue by bbac63** [guildai/guildai-r#4]
I Installed the R package as described in the vignette. However when I call guild_run("train.R") with the example provided I get an error "FileNotFoundError: [WinError 2] The system cannot find the file specified" with the attached traceback

[Log.txt](https://github.com/guildai/guildai-r/files/10609154/Log.txt)

Looks like the error is thrown by subprocess.py.

I am running Windows 10 with the latest miniconda (python 3.10) distribution.

**Comment by t-kalinowski** [comment]
Hello! 

There isn't quite enough in the log to figure out what's wrong. Here are a few ideas:

- Do you have the development version of guild core installed? The R package currently depends on the development version of guild core. You can easily install it using the `install_guild()` R function. (Note that R will prefer the `guild.exe` executable on your PATH, if one is present. It will only use the internal-to-the-R-package version installed by `install_guild()` if `guild.exe` is not already on the PATH. You can check which guild executable is being used with `guildai:::find_guild()`. You'll see `"r-guildai"` in the filepath if the internal-to-the-R-package version is being used.

- Are you running in the context of a project? The quickest way to get started is to setup a new directory with two things in it: the file "train.R" and an empty directory named ".guild". (You can of course put other stuff in there if useful, e.g., a "project-name.Rproj" file, other scripts, etc.). Be sure run `guild_run()` from the directory where the file "train.R" is present.

- I doubt this is the issue, but just in case, on Windows we've generally been testing with the official python binaries from www.python.org (https://www.python.org/ftp/python/3.10.9/python-3.10.9-amd64.exe), not miniconda. On Windows, `install_guild()` will attempt to find python.exe by first checking the PATH, then the registry.

**Comment by bbac63** [comment]
Thank you Tomasz: I checked/tested the above w/o any change. I am running the `guild.exe` under `"r-guildai"` which is installed through `install_guild()`. I also set it up in an empty directory with the respecitve files/folders, but it still fails. I also configured guild.ai on another Windows 10 machine also using miniconda where it worked perfectly. 

An interesting note I found on the guild documentation in section **"Create Output Directories"** where the error is mentioned:

> If the operation saves files to a project subdirectory, the operation must create the subdirectory for each Guild run. Remember, run directories are initially empty. An attempt to save a file to non-existing directory will fail with the message FileNotFoundError: [Errno 2] No such file or directory .... Modify the project code to create missing output directories during operation initialization.

Since the .guild directory is there I am not sure whether this could help on a resolution.

Nevertheless I can use the other machine for the further development of my model.

**Comment by gar1t** [comment]
Hi @bbac63 - thanks for checking out the R support in Guild! I'm sorry you're running into this. It's a very helpful report as I can see Guild is not gracefully handling the environment in your case.

For the sake of readability, I'm including the relevant traceback here:

```
Traceback (most recent call last):
  File "C:\PROGRA~3\MINICO~1\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\PROGRA~3\MINICO~1\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\Scripts\guild.exe\__main__.py", line 7, in <module>
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\main_bootstrap.py", line 29, in main
    _main()
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\main_bootstrap.py", line 54, in _main
    guild.main.main()
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\main.py", line 30, in main
    main_cmd.main(standalone_mode=False)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\click_util.py", line 235, in fn
    return fn0(*(args + (Args(**kw),)))
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run.py", line 737, in run
    run_impl.main(args)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 1693, in main
    _dispatch_op(S)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 1789, in _dispatch_op
    _dispatch_op_cmd(S)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 1995, in _dispatch_op_cmd
    _confirm_and_run(S)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 2072, in _confirm_and_run
    _run(S)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 2271, in _run
    _run_local(S)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 2303, in _run_local
    _run_op(op, S.args)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 2409, in _run_op
    run, exit_status = oplib.run(
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op.py", line 160, in run
    run = init_run(op)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op.py", line 101, in init_run
    _callback("run_initialized", op, run)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op.py", line 90, in _callback
    cb(op, *rest_args)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 1319, in _on_run_initialized
    _copy_run_sourcecode(run, op)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\commands\run_impl.py", line 1338, in _copy_run_sourcecode
    sourcecode_select = op_util.sourcecode_select_for_opdef(opdef)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op_util.py", line 861, in sourcecode_select_for_opdef
    return _builtin_sourcecode_select_rules(opdef) or _project_sourcecode_select_rules(
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op_util.py", line 873, in _project_sourcecode_select_rules
    rules, sourcecode_root = _select_rules_for_opdef(opdef)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op_util.py", line 879, in _select_rules_for_opdef
    return _select_rules_for_opdef_(opdef, sourcecode_root), sourcecode_root
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op_util.py", line 892, in _select_rules_for_opdef_
    _base_sourcecode_select_rules(opdef, sourcecode_root)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op_util.py", line 907, in _base_sourcecode_select_rules
    return _try_vcs_select_rules(sourcecode_root) or _default_select_rules(opdef)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\op_util.py", line 912, in _try_vcs_select_rules
    vcs_rules = vcs_util.project_select_rules(sourcecode_root)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\vcs_util.py", line 272, in project_select_rules
    return git_project_select_rules(project_dir)
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\vcs_util.py", line 276, in git_project_select_rules
    git_ignored = _git_ls_ignored(project_dir, extended_patterns_file=".guildignore")
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\vcs_util.py", line 289, in _git_ls_ignored
    if git_version() < GIT_LS_FILES_TARGET_VER:
  File "C:\Users\BBACHM~1\AppData\Local\R-GUIL~1\lib\site-packages\guild\vcs_util.py", line 481, in git_version
    out = subprocess.check_output(cmd).decode().strip()
  File "C:\PROGRA~3\MINICO~1\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\PROGRA~3\MINICO~1\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\PROGRA~3\MINICO~1\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\PROGRA~3\MINICO~1\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

This means that Guild is not finding `git` on the path when it tries to detect the source code for runs. Guild needs to handle this gracefully with a useful message (we'll get that in for 0.9.0).

I'm assuming you have Git installed on your system, but I wonder if its available on the `PATH` environment variable. Currently Guild requires this (though on Windows perhaps there's another way to find Git - e.g. another environment variable on a Windows registry entry).

If Git is by chance not on your `PATH`, how do you use it? Are you running a GUI app or is it integrated into an IDE?

Sorry again for the hassle - and thanks for your input!

**Comment by bbac63** [comment]
Thx. @gar1t: This solved the problem.

I reinstalled git completely which added the correct path to the `PATH` variable. So far I was using Gihub Desktop which I assume uses an integrated version of git.
